### PR TITLE
Remove duplicate classes before sorting them

### LINKED ISSUE #15: Remove duplicate classes
**Is your feature request related to a problem? Please describe.**
Occasionally I get a bit too zealous with adding tailwind classes, which means I sometimes repeat a couple classes by accident. 

**Describe the solution you'd like**
The sorting helps to discover the duplicates much easier, but was wondering if it be possible to also delete dupes upon sorting?

**Describe alternatives you've considered**
n/a

**Additional context**
❤️

### PR DESCRIPTION
**Pull request by praveenperera**
Closes #15

### CODE REVIEW

**Comment by heybourn** [comment]
You're on fire! Is someone else able to look over this for me? (I'm out at the moment)

**Comment by heybourn** [comment]
cc: @joshmanders

**Comment by praveenperera** [comment]
Good idea @joshmanders, I think the CI would have caught this breaking because lodash was being used while being in devDeps instead of deps right?

**Comment by joshmanders** [comment]
> Good idea @joshmanders, I think a CI would have caught this breaking because lodash was being used while being in devDeps instead of deps right?

That is correct.

**Pull request merged**
