### PR TITLE
Updating Default Sort Order for tailwindcss 2.0

### PR DESCRIPTION
**Pull request by tance77**
I have gone through an added tailwindcss 2.0 classes to this list. I again went down the left side of the documentation page and kept the order as which they appeared on the documentation.

Note Orange was removed from the official docs so I also removed it here. It still can be enabled within the tailwind.config.js file

https://tailwindcss.com/docs/background-color

### CODE REVIEW

**Review by praveenperera — APPROVED** [review]

**Comment by tance77** [comment]
Should we add the colors in tailwind colors to this as well. They are not enabled by default but if enabled it would be nice to have them sorted as well. (Still doesn't include orange, orange was removed.)

**Comment by heybourn** [comment]
Yeah I think adding colours would be a good idea @tance77

**Comment by tance77** [comment]
@heybourn I went and included the optional colors. Orange actually was an optional color. I must have overlooked this.

**Review by praveenperera — APPROVED** [review]

**Comment by praveenperera** [comment]
This looks good, I'm going to merge it. Thanks @tance77 !

**Pull request merged**
