### PR TITLE
[WIP] Add all classes

### PR DESCRIPTION
**Pull request by praveenperera**
Created a default sorter file with all > 16,000 classes created generated by the default Tailwind CSS config.

With this PR classes will be sorted by how they appear in tailwind. One advantage of this is that that all responsive classes `sm:.., xl:...` should also now be sorted properly 

### To Do

- [X] Fix up tests
- [X] Do some manual testing
- [ ] Make PRs for ordering changes in Tailwind CSS, and regenerate sorter
- [ ] Discuss if this is the direction we want to go.

### Future

After this PR, we can look into watching the users `tailwind.config.js` and rebuilding the sorter array from it when it changes.

@heybourn, @joshmanders what do you think?

This would address #52

### CODE REVIEW

**Comment by heybourn** [comment]
Woah! Interesting approach. How necessary is it to have our own file full of classes? Is it not possible to tap into these directly through a Tailwind install?

**Comment by praveenperera** [comment]
It might be possible to use Tailwind to get just a list of class names, I'm not sure I haven't looked into that. 

However, the problem with that would be it would be pretty slow to get tailwind to spit out the list of class names every time headwind has to run. Also since the list of class names would only change if the `tailwind.config.js` file changes this would be a lot of wasted effort.

What I want to do in the future is:

1. Use tailwind to dynamically generate the class names
2. Save the class names to a file
3. Watch tailwind.config.js for changes, and regenerate and save the class names to the file ONLY when it changes

**Comment by Buffalom** [comment]
@praveenperera what's the status of this PR? Any updates?

**Comment by praveenperera** [comment]
@Buffalom I think this approach only makes sense if the order of the classes tailwindcss generates is the same order we want headwind to sort by. I don't think right now it makes sense to order by the order of appearance in tailwind.css. I will close this.

**Pull request closed without merging**
